/*NESTED SUB QUERY:-
-- A sub query written inside a sub query is known as nested sub query.
*/

-- WATD second maximum salary given to an employee
SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL) FROM EMP );

-- WAQTD 3rd maximum salary
SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL) FROM EMP));

-- WAQTD 4rd maximum salary
SELECT MAX(SAL)
FROM EMP
WHERE SAL<(SELECT MAX(SAL) FROM EMP WHERE SAL<
(SELECT MAX(SAL) FROM EMP WHERE SAL<
(SELECT MAX(SAL) FROM EMP)));

-- WAQTD 3rd manimum salary
SELECT Min(SAL)
FROM EMP
WHERE SAL>(SELECT Min(SAL) FROM EMP WHERE SAL>(SELECT Min(SAL) FROM EMP));

-- WAQTD dept name of the emloyee getting 2nd minimum salary
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO 
FROM EMP  
WHERE SAL=(SELECT MIN(SAL)
FROM EMP
WHERE SAL>
(SELECT MIN(SAL) FROM EMP )));


/*REMEMBER:-
1. MAXIMUM use -   MAX() <
2. MINIMUM use -   MIN() >
*/

-- WAQTD name of the emloyee hired before the last employee
SELECT ENAME
FROM EMP
WHERE HIREDATE IN(SELECT HIREDATE FROM EMP WHERE HIREDATE<ALL( SELECT MAX(HIREDATE) FROM EMP ));


/*EMPLOYEE AND MANAGER RELATION*/

-- CASE-1
-- WAQTD name of ALLEN's manager
SELECT ENAME
FROM EMP
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ALLEN');

-- WAQTD name of SMITH's manager's manager
SELECT ENAME
FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH'));

-- WAQTD dname of KING'S manager
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='KING'));

-- WAQTD location of ADAMS's managers manager
SELECT LOC 
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP 
WHERE EMPNO=(SELECT MGR 
FROM EMP
WHERE ENAME='ADAMS')));

/*CASE-2*/
-- WAQTD names of the emloyees reporting to KING
SELECT ENAME
FROM EMP
WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');

-- WAQTD name and salary given to the employees reporting to JAMES
SELECT ENAME,SAL
FROM EMP
WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='JAMES');

#NOTE
-- To find Manager select MGR in sub query
-- To find emloyees select EMPNO in sub query

-- WAQTD dname of the employee reporting to president
SELECT DNAME
FROM DEPT
WHERE DEPTNO=ANY(SELECT DEPTNO FROM EMP WHERE MGR=ANY(SELECT EMPNO FROM EMP WHERE JOB='PRESIDENT'));

-- WAQTD department details of the employees who are reporting to MILLER
SELECT *
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='MILLER'));

-- WAQTD SMITHS reporting manager's name
SELECT ENAME
FROM EMP
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH');

-- WAQTD ADAMS MANAGER'S MANAGER NAME 
SELECT ENAME
FROM EMP
WHERE EMPNO=( SELECT MGR
FROM EMP
WHERE ENAME='ADAMS');

-- WAQTD DNAME OF JONES MANAGER 
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
FROM EMP
WHERE EMPNO=( SELECT MGR FROM EMP
WHERE ENAME='JONES' ));

-- WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL
FROM EMP
WHERE EMPNO=( SELECT MGR
FROM EMP
WHERE ENAME='MILLER');

-- WAQTD LOC OF SMITH'S MANAGER'S MANAGER. 
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP
WHERE EMPNO=( SELECT MGR FROM EMP
WHERE ENAME='SMITH' )));

-- WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL FROM EMP
WHERE EMPNO=( SELECT MGR
FROM EMP
WHERE ENAME='MILLER' );

-- WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC 
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
FROM EMP 
WHERE EMPNO = (SELECT MGR
FROM EMP 
WHERE EMPNO=( SELECT MGR FROM EMP
WHERE ENAME='SMITH' )));

-- WAQTD NAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT ENAME FROM EMP
WHERE MGR=( SELECT EMPNO
FROM EMP WHERE ENAME='BLAKE' );

-- WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(ENAME)
FROM EMP
WHERE MGR=( SELECT EMPNO
FROM EMP
WHERE ENAME='KING');

-- WAQTD number of employees reporting to FORD'S
SELECT COUNT(ENAME)
FROM EMP
WHERE EMPNO=(SELECT MGR
FROM EMP 
WHERE ENAME='FORD');