SELECT *,
	NTILE(3) OVER () AS RELATIVE_rANKING
FROM EMP;


SELECT *,
	NTILE(3) OVER (PARTITION BY DEPTNO) AS RELATIVE_rANKING
FROM EMP;

SELECT *,
	NTILE(3) OVER (ORDER BY SAL) AS RELATIVE_rANKING
FROM EMP;

SELECT *,
	NTILE(3) OVER (PARTITION BY DEPTNO ORDER BY SAL) AS RELATIVE_rANKING
FROM EMP;