SELECT *,
	PERCENT_RANK() OVER () AS RELATIVE_rANKING
FROM EMP;

SELECT *,
	PERCENT_RANK() OVER (PARTITION BY DEPTNO ) AS RELATIVE_rANKING
FROM EMP;

SELECT *,
	PERCENT_RANK() OVER (ORDER BY SAL ) AS RELATIVE_rANKING
FROM EMP;


SELECT *,
	PERCENT_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RELATIVE_rANKING
FROM EMP;